site_name: My Docs

repo_url: https://github.com/MarcoChartier/marcochartier.github.io
repo_name: MarcoChartier/marcochartier.github.io

theme:
  name: material
  palette:
    primary: light blue
  language: fr
  logo: "https://media.giphy.com/media/M9gbBd9nbDrOTu1Mqx/giphy.gif"
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Application d'analyse de projet: Projet.ipynb
  - Documentation technique: Ajouter tableau de bord service.md
  - Applications: applications.md

plugins:
  - mkdocs-jupyter
  - search
  - mermaid2:
      version: 9.4.3
  - mkdocs-video


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


#extra:
#  alternate:
#    - name: English
#      link: /en/ 
#      lang: en
#    - name: Français
#      link: /fr/
#      lang: fr